@startuml rsp-datamodel

class Player{
    -String name
    -int score
}

class Round{
    -final int totalRounds
}

Enum Shape{
    ROCK
    SCISSOR
    PAPER
}


Round *-- Player
Round *-- Shape
@enduml