@startuml rsp-classes
    class RSPGame{
        -Player player1
        -Player player2
        -Round round
        -ArrayList<Player>  players

        +void ChoosePlayer()
        +void setup()
        +void Execute()
        +void Statistics()
        +void RegisterPlayer()
        +void DisplayPlayers()
        +public Player searchPlayer(int id)
    }

    abstract class Player{

        +Player(String name, boolean isHuman)
        +abstract Boolean getIsHuman()
        +abstract int makeMovement()
    }


    class Round{
        -int roundCounter
        -Shape shape

        +Round(Player playerOne, Player playerTwo)
        +void executeRounds()
        +void determinateRoundWinner()
        +void determinateWinner()
    }

    class Human{
        
    }

    class Computer{
        
    }

    RSPGame *-- Player
    RSPGame *-- Round


    Player <|-- Human
    Player <|-- Computer

    Round -right-> Player

@enduml