@startuml RockScissorPaper

object RSPGame
    object Player
            object id
            object name
            object isHuman
        object PlayerGoals
            object makeMovement
            object win
            
    object Human
    object Computer

    object Shapes
        object rock
        object scissor
        object paper
    object Score
        object ScoreGoals
            object displayHistory
            object displayWinner
    object Rounds
        object RoundGoals
            object executeRound
            object determineRoundWinner
            object determineWinner

    RSPGame *-- Player
    RSPGame *-- Rounds

    Rounds *-- RoundGoals
    RoundGoals --> executeRound
    RoundGoals --> determineRoundWinner
    RoundGoals --> determineWinner

    Human -down-|> Player
    Computer -down-|> Player

    Rounds *-- Player
    Rounds --> Shapes
    
    Score *-- ScoreGoals

    Player *-- id
    Player *-- name
    Player *-- isHuman
    Player *-- PlayerGoals
    Player -right-> Shapes

    makeMovement --|> PlayerGoals
    win --|> PlayerGoals

    displayHistory --|> ScoreGoals
    displayWinner --|> ScoreGoals

    Shapes --> rock
    Shapes --> paper
    Shapes --> scissor

    Score -left-> Rounds
@enduml